apiVersion: v1
kind: Pod
metadata:
  name: web-pvc
spec:
  containers:
  - image: nginx:1.14
    name: nginx
    ports:
    - containerPort:  80
    volumeMounts:
    - name: html
      mountPath:  /usr/share/nginx/html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName:  pvc-web