# docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:tag
# kubectl run mysql-env-pod --image=mysql --port=3306 --env=MYSQL_ROOT_PASSWORD=password
kind: Pod
apiVersion: v1
metadata:
  name: mysql-env-pod
spec:
  containers:
  - name: mysql-container
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password