---
apiVersion: v1
kind: Namespace
metadata:
  name: prodns

---
apiVersion: v1
kind: Pod
metadata:
  name: myweb
  namespace: prodns
spec:
  containers:
  - name: myweb-container
    image: nginx:1.14
    resources:
      requests:
        memory: "500Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
    ports:
      - containerPort: 80
        protocol: TCP
    env:
      - name: DB
        value: mydb
