apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  volumes:
  - name: html
    hostPath:
      path: /webdata
  containers:
  - name: web-container
    image: nginx:1.14
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html 