kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  #clusterIP: 10.233.10.10
  selector:
    app: webui
  ports:
  - port: 80
    targetPort: 80
   # nodePort: 30200