kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      name: nfs-server-container
      labels: 
        role: nfs-server
    spec:
      nodeSelector:
        name: node3
        role: nfsserver
      containers: 
      - name: nfs-server
        image:  k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: myshare
          mountPath:  /exports
      volumes:
      - name: myshare
        hostPath:
          path: /share

---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  type: ClusterIP
  clusterIP:  10.233.10.10
  selector:
    role: nfs-server
  ports:
    - name: nfsd
      port: 2049
      targetPort: 2049
    - name: mountd
      port: 20048
      targetPort: 20048
    - name: rpcbind
      port: 111
      targetPort: 111