kind: Deployment
apiVersion: apps/v1
metadata:
  name: blue-deploy
spec:
  selector:
    matchLabels:
      app: web
      version: blue
  replicas: 3
  template:
    metadata:
      name: blue-pod
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: blue-container
        image: whatwant/node-web:2.0
        ports:
        - containerPort: 8080
