apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mainui
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: apache
      rel: stable
  template:
    metadata:
      name: rs-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
      - image:  httpd:2.2
        name: rs-container 
        ports:
        - containerPort: 80
          protocol: TCP